const quotes = [
  { text: "Perseverance is failing 19 times and succeeding the 20th.", author: "Julie Andrews", category: "Motivational", subcategory: "Persistence" },
  { text: "Action is the foundational key to all success.", author: "Pablo Picasso", category: "Motivational", subcategory: "Action" },
  { text: "Life shrinks or expands in proportion to one's courage.", author: "Anaïs Nin", category: "Motivational", subcategory: "Inspiration" },
  { text: "Love recognizes no barriers.", author: "Maya Angelou", category: "Love", subcategory: "Romance" },
  { text: "The love of family and the admiration of friends is much more important than wealth and privilege.", author: "Charles Kuralt", category: "Love", subcategory: "Family" },
  { text: "Friendship is born at that moment when one person says to another: 'What! You too? I thought I was the only one.'", author: "C.S. Lewis", category: "Love", subcategory: "Friendship" },
  { text: "The only true wisdom is in knowing you know nothing.", author: "Socrates", category: "Wisdom", subcategory: "Knowledge" },
  { text: "Life is not measured by the number of breaths we take, but by the moments that take our breath away.", author: "Maya Angelou", category: "Wisdom", subcategory: "Life" },
  { text: "The only source of knowledge is experience.", author: "Albert Einstein", category: "Wisdom", subcategory: "Experience" },
  { text: "Quote 17", author: "Author Unknown", category: "Motivational", subcategory: "Inspiration" },
  { text: "Quote 18", author: "Author Unknown", category: "Wisdom", subcategory: "Life" },
  { text: "Quote 19", author: "Author Unknown", category: "Love", subcategory: "Family" },
  { text: "Quote 20", author: "Author Unknown", category: "Motivational", subcategory: "Inspiration" },
  { text: "Quote 22", author: "Author Unknown", category: "Motivational", subcategory: "Inspiration" },
  { text: "Quote 23", author: "Author Unknown", category: "Love", subcategory: "Family" },
  { text: "Quote 24", author: "Author Unknown", category: "Motivational", subcategory: "Action" },
  { text: "Quote 27", author: "Author Unknown", category: "Motivational", subcategory: "Action" },
  { text: "Quote 29", author: "Author Unknown", category: "Wisdom", subcategory: "Life" },
  { text: "Quote 30", author: "Author Unknown", category: "Love", subcategory: "Friendship" },
  { text: "Quote 31", author: "Author Unknown", category: "Motivational", subcategory: "Inspiration" },
  { text: "Quote 33", author: "Author Unknown", category: "Wisdom", subcategory: "Experience" },
  { text: "Quote 34", author: "Author Unknown", category: "Wisdom", subcategory: "Knowledge" },
  { text: "Quote 37", author: "Author Unknown", category: "Wisdom", subcategory: "Experience" },
  { text: "Quote 38", author: "Author Unknown", category: "Love", subcategory: "Romance" },
  { text: "Quote 39", author: "Author Unknown", category: "Motivational", subcategory: "Action" },
  { text: "Quote 40", author: "Author Unknown", category: "Wisdom", subcategory: "Knowledge" },
  { text: "Quote 41", author: "Author Unknown", category: "Love", subcategory: "Romance" },
  { text: "Quote 44", author: "Author Unknown", category: "Love", subcategory: "Friendship" },
  { text: "Quote 45", author: "Author Unknown", category: "Wisdom", subcategory: "Life" },
  { text: "Quote 46", author: "Author Unknown", category: "Wisdom", subcategory: "Knowledge" },
  { text: "Quote 47", author: "Author Unknown", category: "Love", subcategory: "Family" },
  { text: "Quote 50", author: "Author Unknown", category: "Love", subcategory: "Friendship" }
];

export default quotes;